document.addEventListener('DOMContentLoaded', function() {
    const loginForm = document.getElementById('loginForm');
    const roleSelect = document.getElementById('role');
    const usernameInput = document.getElementById('username');
    const passwordInput = document.getElementById('password');
    const formError = document.getElementById('formError');
    const loginBtn = document.querySelector('.login-btn');

    // Simple function to display error messages
    function displayError(message) {
        if (formError) {
            formError.textContent = message;
            formError.style.display = 'block';
        }
    }

    // Function to clear errors (used when user starts typing)
    function clearError() {
        if (formError) {
            formError.textContent = '';
            // Only hide if the error message was generated by JS, not PHP
            if (formError.getAttribute('data-php-error') !== 'true') {
                 formError.style.display = 'none';
            }
        }
    }

    // --- 1. Client-Side Validation and Submission Handling ---
    if (loginForm) {
        loginForm.addEventListener('submit', function(e) {
            clearError();

            const role = roleSelect.value;
            const username = usernameInput.value.trim();
            const password = passwordInput.value.trim();

            if (!role) {
                displayError("Please select your access role.");
                e.preventDefault();
                return;
            }
            if (username === '') {
                displayError("Username/ID field cannot be empty.");
                e.preventDefault();
                return;
            }
            if (password === '') {
                displayError("Password field cannot be empty.");
                e.preventDefault();
                return;
            }
            
            // If validation passes, allow PHP submission to proceed.
            // Disable button during submission to prevent double-click
            loginBtn.disabled = true;
            loginBtn.querySelector('.btn-text').textContent = 'Authenticating...';
            // DO NOT call e.preventDefault() here. Let the form submit to PHP.
        });

        // --- 2. Input Focus and Error Clean up ---
        document.querySelectorAll('.input-group input, .input-group select').forEach(input => {
            // Clear any displayed errors as soon as the user starts interacting
            input.addEventListener('input', clearError);
            input.addEventListener('change', clearError);
        });

        // Handle case where PHP returns an error (to re-enable the button)
        if (formError && formError.style.display === 'block') {
            // Mark the error as being from PHP, and re-enable the button
            formError.setAttribute('data-php-error', 'true');
            if (loginBtn) {
                 loginBtn.disabled = false;
                 loginBtn.querySelector('.btn-text').textContent = 'Log In';
            }
        }
    }
});